### ISSUE TITLE
Question about gorilla-core version

### ISSUE THREAD

**Issue by taeyeopl** [CVMI-Lab/IST-Net#5]
I'm currently using a recent gorilla-core (0.2.7.8), and it looks like some issues depending on the gorilla-core version. 
Can you share which version you use for gorilla-core? These are the errors that I got.

`
Traceback (most recent call last):
  File "train.py", line 192, in <module>
    start_iter=start_iter)
  File "/home/miruware/workspace/IST-Net/utils/solver.py", line 25, in __init__
    logger=logger)
  File "/home/miruware/anaconda3/envs/istnet/lib/python3.6/site-packages/gorilla/solver/base_solver.py", line 39, in __init__
    self.optimizer = build_optimizer(model, cfg.optimizer)
  File "/home/miruware/anaconda3/envs/istnet/lib/python3.6/site-packages/gorilla/solver/build.py", line 68, in build_optimizer
    return build_single_optimizer(model, _optimizer_cfg)
  File "/home/miruware/anaconda3/envs/istnet/lib/python3.6/site-packages/gorilla/solver/build.py", line 45, in build_single_optimizer
    return _build_optimizer(optimizer_cfg)
  File "/home/miruware/anaconda3/envs/istnet/lib/python3.6/site-packages/gorilla/core/registry.py", line 163, in build_from_cfg
    raise KeyError("cfg or default_args must contain the key "
KeyError: "`cfg` or `default_args` must contain the key 'type', but got {'name': 'Adam', 'lr': 0.01, 'betas': [0.5, 0.999], 'eps': 1e-06, 'weight_decay': 0, 'params': [{'params': <filter object at 0x7f15bb53c710>}]}\nNone"
`

**Comment by Eddieeee-Liu** [comment]
Hi, my gorilla-core version is 0.2.7.8. I set up a new environment and try to reproduce this error, but every thing goes right. I think you may make some mistake when setting up the environment. Please check the package step by step.

**Comment by taeyeopl** [comment]
Thanks for your reply. I have solved changing the config file `name` to `type` temporarily.

https://github.com/CVMI-Lab/IST-Net/blob/169e1cf7ee2d2a56fdeee4a0d755b85df2330e7a/config/ist_net_default.yaml#L5

ex) type : Adam

**Comment by pppkkk611** [comment]
> Thanks for your reply. I have solved changing the config file to temporarily.`name``type`
> 
> https://github.com/CVMI-Lab/IST-Net/blob/169e1cf7ee2d2a56fdeee4a0d755b85df2330e7a/config/ist_net_default.yaml#L5
> 
> ex) type : Adam

optimizer:
  **type** : Adam
  lr   : 0.01
  betas: [0.5, 0.999]
  eps  : 0.000001
  weight_decay: 0

lr_scheduler:
  **type**: StepLR
  step_size: 1
  gamma: 0.5

but still has problem：
TypeError: step() missing 1 required positional argument: 'step'
